name: soul ci
on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  deploy:
    name: Test and Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: |
          cd soul-ui 
          npm install --frozen-lockfile --prefer-offline

      - name: Test
        run: |
          cd soul-ui
          npm run lint

      - name: Build
        run: |
          cd soul-ui
          npm run build
